# Generated by Django 5.1.6 on 2025-02-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userid',
            name='Email',
            field=models.EmailField(max_length=20),
        ),
    ]
